version: '3.8'

services:
    app:
        build:
            context: .
            dockerfile: docker/Dockerfile
        container_name: symfony_app
        volumes:
            - .:/var/www/symfony
        working_dir: /var/www/symfony
        expose:
            - "9000"  # PHP-FPM port
        depends_on:
            mysql:
                condition: service_healthy
            rabbitmq:
                condition: service_healthy
        networks:
            - shared-rabbit
            - symfony

    nginx:
        image: nginx:alpine
        container_name: symfony_nginx
        ports:
            - "8001:80"  # expose to your machine (changed port to 8001)
        volumes:
            - .:/var/www/symfony
            - ./docker/nginx/symfony.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - app
        networks:
            - symfony

    mysql:
        image: mysql:8.0
        container_name: symfony_mysql
        restart: always
        ports:
            - "3307:3306"
        volumes:
            - mysql_data:/var/lib/mysql
        networks:
            - symfony
        healthcheck:
            test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
            interval: 10s
            timeout: 5s
            retries: 5

    rabbitmq:
        image: rabbitmq:3-management
        container_name: symfony_rabbitmq
        ports:
            - "5673:5672"
            - "15673:15672"
        healthcheck:
            test: ["CMD", "rabbitmqctl", "status"]
            interval: 10s
            timeout: 5s
            retries: 5
        networks:
            - shared-rabbit

volumes:
    mysql_data:

networks:
    symfony:
        driver: bridge

    shared-rabbit:
        external: true
